export const GET_DASHBOARD_JOBS_SUCCESS = "GET_DASHBOARD_JOBS_SUCCESS";
export const GET_DASHBOARD_JOBS_LOADING = "GET_DASHBOARD_JOBS_LOADING";
export const GET_DASHBOARD_JOBS_FAILURE = "GET_DASHBOARD_JOBS_FAILURE";